language: node_js
node_js:
  - "node"
  - "iojs"

addons:
  code_climate:
    repo_token: c431e390

after_script:
  - codeclimate < coverage/lcov.info

notifications:
  email:
    - jeremy.dagorn@gmail.com
